# Generated by Django 4.1.7 on 2023-02-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9, null=True)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('empty_slots', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('altitude', models.IntegerField()),
                ('ebikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('normal_bikes', models.IntegerField()),
                ('payment', models.JSONField()),
                ('payment_terminal', models.BooleanField()),
                ('post_code', models.CharField(max_length=20)),
                ('renting', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('uid', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
