# Generated by Django 4.1.7 on 2023-02-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stations_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('typology', models.CharField(max_length=10)),
                ('responsible', models.CharField(max_length=100)),
                ('investment', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
