# Generated by Django 4.1.7 on 2023-02-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsible',
            field=models.CharField(max_length=250),
        ),
    ]
