# Generated by Django 4.1.7 on 2023-02-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_proyecto_name_alter_proyecto_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='name',
            field=models.TextField(),
        ),
    ]
