# Generated by Django 4.1.7 on 2023-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stations_address_alter_stations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
