# Generated by Django 4.1.7 on 2023-05-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stations_altitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Expediente')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad Fiscalizable')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o razón social')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('detalle', models.URLField(verbose_name='Enlace detalle')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-id']},
        ),
    ]
