# Generated by Django 4.1.7 on 2023-05-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_procedimientos_alter_proyecto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='expediente',
            field=models.CharField(default=0, max_length=25, verbose_name='Expediente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro'),
        ),
    ]
