# Generated by Django 4.1.7 on 2023-05-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_procedimientos_expediente_alter_procedimientos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='categoria',
            field=models.CharField(default=0, max_length=60, verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
