# Generated by Django 4.1.7 on 2023-05-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_procedimientos_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientos',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name='Categoría'),
        ),
    ]
