# Generated by Django 4.1.7 on 2023-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_procedimientos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientos',
            name='nombre',
            field=models.CharField(max_length=400, verbose_name='Nombre o razón social'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='unidad',
            field=models.CharField(max_length=400, verbose_name='Unidad Fiscalizable'),
        ),
    ]
